### ISSUE TITLE
Agenda 2022-01-31 - please comment!

### ISSUE THREAD

**Issue by AlyciaWinters** [NDCLab/social-context-eeg-dataset#3]
- Welcome to new RAs!
- Join weekly EEG trainings
- Updates on task triggers, script, REDCap
- After Emily and I met earlier today we had some questions/concerns about when they complete the questionnaires
- Next steps (e.g., how many people do we want to pilot?)

**Comment by georgebuzzell** [comment]
thanks @AlyciaWinters Some additional items:

Status updates on irb/ccf onboarding
Status update on Redcap set up
Status update on protocol 
Blocks/challenges (what needs to be done to run a full pilot)
Setting a date for our first pilot
Setting a date for live sona recruitment (even if still considered pilots)

**Comment by AlyciaWinters** [comment]
- Decide things to cut from questionnaires to lessen the time 
-
