### ISSUE TITLE
Agenda 2022-02-14 - Please comment!

### ISSUE THREAD

**Issue by AlyciaWinters** [NDCLab/social-context-eeg-dataset#9]
Notes from the first two pilot sessions:

1. After trying putting electrodes in the cap using the mannequin head, we were able to cut that part down to ~25 minutes. Also helped with wire management significantly so I think that is necessary for this many electrodes!
2. The questionnaires take ~35 minutes. 
3. The timing for actually gelling got messed up by the issues with the amp we ran into, but I think it was ~30-35 minutes after figuring that out
4. Need to adjust to task trials/blocks again - they are running longer than 20 minutes for some reason.
5. Were not able to run through entire study because of the other issues 
6. Is reading the practice instructions completely necessary?
7. Currently having to use my laptop for questionnaires is very awkward and time consuming (I cannot turn off the lock/screen saving feature and regularly need to have to log in numerous times) - will we have an iPad to use for the next couple of pilots?
8. I think I heard something about the prior participants answers being filled in during the second pilot (but Emily can correct me if I misheard)
     - Emily: correct! A solution would be to incognito tab the RedCap survey, since it wouldn't read in saved or entered information
9. Do we want to save the EEG data as one file? or split by condition? split by task and condition?
10. The study may actually need 3.5 hours instead of 3, but might need to come back to this after we run through the full study without significant issues

**Comment by emach039** [comment]
Additional comments
1. Issue with task programming
      - Stimulus input at times doesn't register immediately after clicking on the pad, so the stimulus will stay on screen up until the max allotted time has passed
           - Not tied to any specific stimuli from what I watched
           - Not an issue with pressing hard enough on keypad. At some point, Sophia pressed the key twice and it still did not leave
      - For practice version of experiment, the Switch condition indicators don't show up (i.e participants don't know what aspect to focus on for any trials) 

2. Issue with ears not falling directly inside cap hole; what happens to those electrodes?
3. For night participants runs, might be an issue. For both of our pilot runs, a custodian entered the room. Not sure if she's aware people run experiments at this time? 
4. The "Update windows subscription" thing that pops up seemingly didn't pop up during the tasks, but at one point there was a stutter in the task where the stimulus flickered immediately in and out without input; might be tied to this, since it happened only once? Or an oddity in the script?

**Comment by georgebuzzell** [comment]
Thank you, @AlyciaWinters and @emach039!

@emach039 very clever solution in terms of using incognito mode; I agree!

@AlyciaWinters and @emach039 it sounds like the primary issue currently is the issue with the task programming. I think this should be a major focus to tackle, as it might be tricky to resolve. @AlyciaWinters do you have additional details/insight into the nature of the issues that @emach039 reported? Have you been able to replicate/look into the source of the issues? Does this only occur on the lab EEG computer or present on your computer as well (which I think is what you were using to modify the task, etc). Relatedly, have you had a chance to reach out to @kianooshhosseini about this?

@emach039 thank you for mentioning the update windows issues. Keen observation that, although it did not show up, the flicker very well could have been a result of this. I was initially under the impression that IT disabled this from auto-running (I thought I asked for that, for this reason) but I could be mistaken, etc. Either way, THANK YOU for mentioning this and this is a high priority to resolve as well. Essentially, we need to turn off all auto-run processes. The catch is, we may or may not have the admin privileges to do so without campus IT.
